/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerOption {
  'id' : bigint,
  'text' : string,
  'correct' : boolean,
}
export interface AnswerOptionInput { 'text' : string, 'correct' : boolean }
export interface AttemptAnswer {
  'questionId' : QuestionId,
  'selectedOptionIds' : Array<bigint>,
}
export type AttemptId = bigint;
export interface AttemptInput {
  'answers' : Array<AttemptAnswer>,
  'quizId' : QuizId,
}
export interface AttemptPublic {
  'id' : AttemptId,
  'maxScore' : bigint,
  'answers' : Array<AttemptAnswer>,
  'createdAt' : Timestamp,
  'score' : bigint,
  'quizId' : QuizId,
  'passed' : boolean,
}
export type CategoryId = bigint;
export interface CategoryPublic {
  'id' : CategoryId,
  'sortOrder' : bigint,
  'name' : string,
  'itemCount' : bigint,
  'positionId' : PositionId,
  'coverPhoto' : ExternalBlob,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type FontChoice = { 'sansSerif' : null } |
  { 'monospace' : null } |
  { 'serif' : null } |
  { 'systemFont' : null };
export type ItemId = bigint;
export interface MenuItemPublic {
  'id' : ItemId,
  'categoryId' : CategoryId,
  'name' : string,
  'description' : string,
  'instructions' : Array<string>,
  'subCategoryId' : [] | [SubCategoryId],
  'itemPhoto' : ExternalBlob,
  'ingredients' : Array<string>,
}
export type PositionId = bigint;
export interface PositionPublic {
  'id' : PositionId,
  'sortOrder' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'coverPhoto' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'categoryCount' : bigint,
}
export type Principal = Principal;
export interface QuestionEdit {
  'text' : string,
  'questionType' : QuestionType,
  'options' : Array<AnswerOptionInput>,
}
export type QuestionId = bigint;
export interface QuestionInput {
  'text' : string,
  'questionType' : QuestionType,
  'options' : Array<AnswerOptionInput>,
}
export interface QuestionPublic {
  'id' : QuestionId,
  'order' : bigint,
  'text' : string,
  'questionType' : QuestionType,
  'quizId' : QuizId,
  'options' : Array<AnswerOption>,
}
export type QuestionType = { 'multiple' : null } |
  { 'single' : null };
export interface QuizEdit {
  'title' : string,
  'description' : [] | [string],
  'passingPercentage' : bigint,
}
export type QuizId = bigint;
export interface QuizInput {
  'title' : string,
  'description' : [] | [string],
  'passingPercentage' : bigint,
}
export interface QuizPublic {
  'id' : QuizId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'positionId' : PositionId,
  'updatedAt' : Timestamp,
  'passingPercentage' : bigint,
  'questionCount' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type SubCategoryId = bigint;
export interface SubCategoryPublic {
  'id' : SubCategoryId,
  'sortOrder' : bigint,
  'name' : string,
  'itemCount' : bigint,
  'parentCategoryId' : CategoryId,
  'coverPhoto' : ExternalBlob,
}
export interface ThemePublic {
  'font' : FontChoice,
  'primaryColor' : string,
  'logo' : [] | [ExternalBlob],
  'accentColor' : string,
  'updatedAt' : Timestamp,
}
export type Timestamp = bigint;
export interface TrainingStepEdit {
  'video' : [] | [ExternalBlob],
  'text' : string,
  'photo' : [] | [ExternalBlob],
}
export interface TrainingStepInput {
  'video' : [] | [ExternalBlob],
  'text' : string,
  'photo' : [] | [ExternalBlob],
}
export interface TrainingStepPublic {
  'id' : bigint,
  'itemId' : ItemId,
  'order' : bigint,
  'video' : [] | [ExternalBlob],
  'text' : string,
  'photo' : [] | [ExternalBlob],
}
export interface UserProfilePublic {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__categories' : ActorMethod<[], any>,
  '__items' : ActorMethod<[], any>,
  '__positions' : ActorMethod<[], any>,
  '__quizAttempts' : ActorMethod<[], any>,
  '__quizQuestions' : ActorMethod<[], any>,
  '__quizState' : ActorMethod<[], any>,
  '__quizzes' : ActorMethod<[], any>,
  '__state' : ActorMethod<[], any>,
  '__steps' : ActorMethod<[], any>,
  '__subCategories' : ActorMethod<[], any>,
  '__theme' : ActorMethod<[], any>,
  '__trainingState' : ActorMethod<[], any>,
  '__users' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], UserProfilePublic>,
  'createCategory' : ActorMethod<
    [PositionId, string, ExternalBlob],
    CategoryId
  >,
  'createMenuItem' : ActorMethod<
    [CategoryId, [] | [SubCategoryId], string, string, ExternalBlob],
    ItemId
  >,
  'createPosition' : ActorMethod<
    [string, [] | [string], [] | [ExternalBlob]],
    PositionId
  >,
  'createQuestion' : ActorMethod<[QuizId, QuestionInput], QuestionPublic>,
  'createQuiz' : ActorMethod<[PositionId, QuizInput], QuizId>,
  'createSubCategory' : ActorMethod<
    [CategoryId, string, ExternalBlob],
    SubCategoryPublic
  >,
  'createTrainingStep' : ActorMethod<
    [ItemId, TrainingStepInput],
    TrainingStepPublic
  >,
  'deleteCategory' : ActorMethod<[CategoryId], bigint>,
  'deleteMenuItem' : ActorMethod<[ItemId], undefined>,
  'deletePosition' : ActorMethod<[PositionId], bigint>,
  'deleteQuestion' : ActorMethod<[QuestionId], boolean>,
  'deleteQuiz' : ActorMethod<[QuizId], boolean>,
  'deleteSubCategory' : ActorMethod<[SubCategoryId], { 'itemCount' : bigint }>,
  'deleteTrainingStep' : ActorMethod<[bigint], boolean>,
  'editTrainingStep' : ActorMethod<
    [bigint, TrainingStepEdit],
    TrainingStepPublic
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[ItemId], [] | [MenuItemPublic]>,
  'getPosition' : ActorMethod<[PositionId], [] | [PositionPublic]>,
  'getQuizWithQuestions' : ActorMethod<
    [QuizId],
    [] | [{ 'quiz' : QuizPublic, 'questions' : Array<QuestionPublic> }]
  >,
  'getTheme' : ActorMethod<[], ThemePublic>,
  'getTrainingStep' : ActorMethod<[bigint], [] | [TrainingStepPublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<CategoryPublic>>,
  'listItemsByCategory' : ActorMethod<[CategoryId], Array<MenuItemPublic>>,
  'listItemsBySubCategory' : ActorMethod<
    [SubCategoryId],
    Array<MenuItemPublic>
  >,
  'listMyQuizAttempts' : ActorMethod<[QuizId], Array<AttemptPublic>>,
  'listPositions' : ActorMethod<[], Array<PositionPublic>>,
  'listQuizzesByPosition' : ActorMethod<[PositionId], Array<QuizPublic>>,
  'listSubCategories' : ActorMethod<[CategoryId], Array<SubCategoryPublic>>,
  'listTrainingSteps' : ActorMethod<[ItemId], Array<TrainingStepPublic>>,
  'listUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'moveQuestion' : ActorMethod<[QuestionId, bigint], boolean>,
  'moveTrainingStep' : ActorMethod<[bigint, bigint], boolean>,
  'resetTheme' : ActorMethod<[], ThemePublic>,
  'revokeRole' : ActorMethod<[Principal], UserProfilePublic>,
  'saveCallerUserProfile' : ActorMethod<[string], UserProfilePublic>,
  'searchItems' : ActorMethod<[string], Array<MenuItemPublic>>,
  'searchItemsInCategory' : ActorMethod<
    [CategoryId, string],
    Array<MenuItemPublic>
  >,
  'setCategorySortOrder' : ActorMethod<[CategoryId, bigint], undefined>,
  'setPositionSortOrder' : ActorMethod<[PositionId, bigint], undefined>,
  'setSubCategorySortOrder' : ActorMethod<[SubCategoryId, bigint], undefined>,
  'submitQuizAttempt' : ActorMethod<[AttemptInput], AttemptPublic>,
  'updateCategory' : ActorMethod<
    [CategoryId, PositionId, string, ExternalBlob],
    undefined
  >,
  'updateLogo' : ActorMethod<[[] | [ExternalBlob]], ThemePublic>,
  'updateMenuItem' : ActorMethod<
    [ItemId, CategoryId, [] | [SubCategoryId], string, string, ExternalBlob],
    undefined
  >,
  'updateMenuItemRecipe' : ActorMethod<
    [ItemId, Array<string>, Array<string>],
    undefined
  >,
  'updatePosition' : ActorMethod<
    [PositionId, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'updateQuestion' : ActorMethod<[QuestionId, QuestionEdit], QuestionPublic>,
  'updateQuiz' : ActorMethod<[QuizId, QuizEdit], undefined>,
  'updateSubCategory' : ActorMethod<
    [SubCategoryId, string, ExternalBlob],
    SubCategoryPublic
  >,
  'updateTheme' : ActorMethod<
    [[] | [string], [] | [string], [] | [FontChoice]],
    ThemePublic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];