/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Timestamp = IDL.Nat;
export const UserProfilePublic = IDL.Record({
  'principal' : Principal,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CategoryId = IDL.Nat;
export const SubCategoryId = IDL.Nat;
export const ItemId = IDL.Nat;
export const SubCategoryPublic = IDL.Record({
  'id' : SubCategoryId,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'itemCount' : IDL.Nat,
  'parentCategoryId' : CategoryId,
  'coverPhoto' : ExternalBlob,
});
export const TrainingStepInput = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const TrainingStepPublic = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : ItemId,
  'order' : IDL.Nat,
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const TrainingStepEdit = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const MenuItemPublic = IDL.Record({
  'id' : ItemId,
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'subCategoryId' : IDL.Opt(SubCategoryId),
  'itemPhoto' : ExternalBlob,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const FontChoice = IDL.Variant({
  'sansSerif' : IDL.Null,
  'monospace' : IDL.Null,
  'serif' : IDL.Null,
  'systemFont' : IDL.Null,
});
export const ThemePublic = IDL.Record({
  'font' : FontChoice,
  'primaryColor' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'accentColor' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const CategoryPublic = IDL.Record({
  'id' : CategoryId,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'itemCount' : IDL.Nat,
  'coverPhoto' : ExternalBlob,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__categories' : IDL.Func([], [IDL.Reserved], ['query']),
  '__items' : IDL.Func([], [IDL.Reserved], ['query']),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  '__steps' : IDL.Func([], [IDL.Reserved], ['query']),
  '__subCategories' : IDL.Func([], [IDL.Reserved], ['query']),
  '__theme' : IDL.Func([], [IDL.Reserved], ['query']),
  '__trainingState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__users' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([Principal, UserRole], [UserProfilePublic], []),
  'createCategory' : IDL.Func([IDL.Text, ExternalBlob], [CategoryId], []),
  'createMenuItem' : IDL.Func(
      [CategoryId, IDL.Opt(SubCategoryId), IDL.Text, IDL.Text, ExternalBlob],
      [ItemId],
      [],
    ),
  'createSubCategory' : IDL.Func(
      [CategoryId, IDL.Text, ExternalBlob],
      [SubCategoryPublic],
      [],
    ),
  'createTrainingStep' : IDL.Func(
      [ItemId, TrainingStepInput],
      [TrainingStepPublic],
      [],
    ),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Nat], []),
  'deleteMenuItem' : IDL.Func([ItemId], [], []),
  'deleteSubCategory' : IDL.Func(
      [SubCategoryId],
      [IDL.Record({ 'itemCount' : IDL.Nat })],
      [],
    ),
  'deleteTrainingStep' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editTrainingStep' : IDL.Func(
      [IDL.Nat, TrainingStepEdit],
      [TrainingStepPublic],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([ItemId], [IDL.Opt(MenuItemPublic)], ['query']),
  'getTheme' : IDL.Func([], [ThemePublic], ['query']),
  'getTrainingStep' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TrainingStepPublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
  'listItemsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(MenuItemPublic)],
      ['query'],
    ),
  'listItemsBySubCategory' : IDL.Func(
      [SubCategoryId],
      [IDL.Vec(MenuItemPublic)],
      ['query'],
    ),
  'listSubCategories' : IDL.Func(
      [CategoryId],
      [IDL.Vec(SubCategoryPublic)],
      ['query'],
    ),
  'listTrainingSteps' : IDL.Func(
      [ItemId],
      [IDL.Vec(TrainingStepPublic)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'moveTrainingStep' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'resetTheme' : IDL.Func([], [ThemePublic], []),
  'revokeRole' : IDL.Func([Principal], [UserProfilePublic], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItemPublic)], ['query']),
  'searchItemsInCategory' : IDL.Func(
      [CategoryId, IDL.Text],
      [IDL.Vec(MenuItemPublic)],
      ['query'],
    ),
  'setCategorySortOrder' : IDL.Func([CategoryId, IDL.Nat], [], []),
  'setSubCategorySortOrder' : IDL.Func([SubCategoryId, IDL.Nat], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text, ExternalBlob], [], []),
  'updateLogo' : IDL.Func([IDL.Opt(ExternalBlob)], [ThemePublic], []),
  'updateMenuItem' : IDL.Func(
      [
        ItemId,
        CategoryId,
        IDL.Opt(SubCategoryId),
        IDL.Text,
        IDL.Text,
        ExternalBlob,
      ],
      [],
      [],
    ),
  'updateMenuItemRecipe' : IDL.Func(
      [ItemId, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateSubCategory' : IDL.Func(
      [SubCategoryId, IDL.Text, ExternalBlob],
      [SubCategoryPublic],
      [],
    ),
  'updateTheme' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(FontChoice)],
      [ThemePublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Timestamp = IDL.Nat;
  const UserProfilePublic = IDL.Record({
    'principal' : Principal,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CategoryId = IDL.Nat;
  const SubCategoryId = IDL.Nat;
  const ItemId = IDL.Nat;
  const SubCategoryPublic = IDL.Record({
    'id' : SubCategoryId,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'itemCount' : IDL.Nat,
    'parentCategoryId' : CategoryId,
    'coverPhoto' : ExternalBlob,
  });
  const TrainingStepInput = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const TrainingStepPublic = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : ItemId,
    'order' : IDL.Nat,
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const TrainingStepEdit = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const MenuItemPublic = IDL.Record({
    'id' : ItemId,
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'subCategoryId' : IDL.Opt(SubCategoryId),
    'itemPhoto' : ExternalBlob,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const FontChoice = IDL.Variant({
    'sansSerif' : IDL.Null,
    'monospace' : IDL.Null,
    'serif' : IDL.Null,
    'systemFont' : IDL.Null,
  });
  const ThemePublic = IDL.Record({
    'font' : FontChoice,
    'primaryColor' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'accentColor' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const CategoryPublic = IDL.Record({
    'id' : CategoryId,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'itemCount' : IDL.Nat,
    'coverPhoto' : ExternalBlob,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__categories' : IDL.Func([], [IDL.Reserved], ['query']),
    '__items' : IDL.Func([], [IDL.Reserved], ['query']),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    '__steps' : IDL.Func([], [IDL.Reserved], ['query']),
    '__subCategories' : IDL.Func([], [IDL.Reserved], ['query']),
    '__theme' : IDL.Func([], [IDL.Reserved], ['query']),
    '__trainingState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__users' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([Principal, UserRole], [UserProfilePublic], []),
    'createCategory' : IDL.Func([IDL.Text, ExternalBlob], [CategoryId], []),
    'createMenuItem' : IDL.Func(
        [CategoryId, IDL.Opt(SubCategoryId), IDL.Text, IDL.Text, ExternalBlob],
        [ItemId],
        [],
      ),
    'createSubCategory' : IDL.Func(
        [CategoryId, IDL.Text, ExternalBlob],
        [SubCategoryPublic],
        [],
      ),
    'createTrainingStep' : IDL.Func(
        [ItemId, TrainingStepInput],
        [TrainingStepPublic],
        [],
      ),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Nat], []),
    'deleteMenuItem' : IDL.Func([ItemId], [], []),
    'deleteSubCategory' : IDL.Func(
        [SubCategoryId],
        [IDL.Record({ 'itemCount' : IDL.Nat })],
        [],
      ),
    'deleteTrainingStep' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editTrainingStep' : IDL.Func(
        [IDL.Nat, TrainingStepEdit],
        [TrainingStepPublic],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([ItemId], [IDL.Opt(MenuItemPublic)], ['query']),
    'getTheme' : IDL.Func([], [ThemePublic], ['query']),
    'getTrainingStep' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TrainingStepPublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
    'listItemsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(MenuItemPublic)],
        ['query'],
      ),
    'listItemsBySubCategory' : IDL.Func(
        [SubCategoryId],
        [IDL.Vec(MenuItemPublic)],
        ['query'],
      ),
    'listSubCategories' : IDL.Func(
        [CategoryId],
        [IDL.Vec(SubCategoryPublic)],
        ['query'],
      ),
    'listTrainingSteps' : IDL.Func(
        [ItemId],
        [IDL.Vec(TrainingStepPublic)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'moveTrainingStep' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'resetTheme' : IDL.Func([], [ThemePublic], []),
    'revokeRole' : IDL.Func([Principal], [UserProfilePublic], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
    'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItemPublic)], ['query']),
    'searchItemsInCategory' : IDL.Func(
        [CategoryId, IDL.Text],
        [IDL.Vec(MenuItemPublic)],
        ['query'],
      ),
    'setCategorySortOrder' : IDL.Func([CategoryId, IDL.Nat], [], []),
    'setSubCategorySortOrder' : IDL.Func([SubCategoryId, IDL.Nat], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text, ExternalBlob], [], []),
    'updateLogo' : IDL.Func([IDL.Opt(ExternalBlob)], [ThemePublic], []),
    'updateMenuItem' : IDL.Func(
        [
          ItemId,
          CategoryId,
          IDL.Opt(SubCategoryId),
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [],
        [],
      ),
    'updateMenuItemRecipe' : IDL.Func(
        [ItemId, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateSubCategory' : IDL.Func(
        [SubCategoryId, IDL.Text, ExternalBlob],
        [SubCategoryPublic],
        [],
      ),
    'updateTheme' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(FontChoice)],
        [ThemePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };